### ISSUE TITLE
Fix eslint

### ISSUE THREAD

**Issue by daiyanze** [Pitayan/gatsby-theme-pitayan#21]

**Comment by panzerstadt** [comment]
<img src="https://media2.giphy.com/media/OmK8lulOMQ9XO/giphy.gif"/>

**Comment by daiyanze** [comment]
@panzerstadt Maybe this issue too boring XD? There's another one of implementing commenting function.

**Comment by panzerstadt** [comment]
Nono that gif is meant to say I’m excited to start contributing! XD

**Comment by panzerstadt** [comment]
hmm can you give me more context? i tried running:

# To start local development
$ npm -w packages/www run develop

the www package doesn't seem to have any issues, or rather it doesn't have any code that needs linting.

the gateby-theme-pitayan refuses to build due to gatsby-config not being able to be exported as a function. 

![image](https://user-images.githubusercontent.com/18601248/219365245-a5a03619-5653-4e53-89d6-b482585e520a.png)


would appreciate some pointers on where to look! (as well as how to setup)

**Comment by daiyanze** [comment]
How was the `npm i`? Hope it was a clean installation with no errors. (Btw, need to use Node 18+)

And which directory were you at while executing the command of `npm -w packages/www run develop`?

**Comment by panzerstadt** [comment]
ok played around with it more and realised i'm not supposed to run develop on the plugin itself (sidenote: if the scripts on packages/gatsby-theme-pitayan are not supposed to be run, perhaps we should remove them)

**Comment by panzerstadt** [comment]
```
warn gatsby-plugin-react-helmet: Gatsby now has built-in support for modifying the document head. Learn more at https://gatsby.dev/gatsby-head
warn Plugin `@pitayan/gatsby-theme-pitayan` has customized the GraphQL type `Mdx`, which has already been defined by the plugin
`gatsby-plugin-mdx`. This could potentially cause conflicts.
warn There are conflicting field types in your data.
warn You can't use childImageSharp together with SiteLogo.svg — use publicURL instead. The childImageSharp portion of the query in this file
will return null: undefined
```

are these the eslint warnings that you're looking to fix?

**Comment by daiyanze** [comment]
Em... That means eslint is still working on your side? If so, I think we could close this ticket asap

**Comment by panzerstadt** [comment]
i guess eslint is still working as expected.
